language: node_js

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - 'npm install -g npm@latest'

script:
  - 'npm test'

node_js:
  - 0.8
  - 0.10
  - 0.11
